dmdma/applications/iframes/__init__.py
from flask import Blueprint, g, redirect, render_template, url_for
from flask.cli import with_appcontext

from .iframe import iframe_item

# Customise linked iframes here

IFRAMES_COLLECTION=[iframe_item(name = 'example.com',
                                description = 'Example of including a website.',
                                url = 'https://example.com'),
                    iframe_item(name = 'My Blog',
                                description = 'Example of including a website.',
                                url = 'https://datablog.roman-halliday.com'),
                    iframe_item(name = 'Simple File Access',
                                description = 'Example of file listing (via Apache), perhaps a simple solution to distributing that internal weekly CSV report that X department insists on having.',
                                url = 'https://www.roman-halliday.com/js_tools/')
    ]

bp = Blueprint('iframes', __name__, url_prefix='/iframes')
    
@with_appcontext
@bp.route('/')
def home():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    return render_template('iframes/home.html', iframes_collection = IFRAMES_COLLECTION)

#iframe_item

@with_appcontext
@bp.route('/<int:iframe_id>')
def if_item(iframe_id):
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    ifreame_item = IFRAMES_COLLECTION[iframe_id]
    return render_template('iframes/home.html', iframes_collection = IFRAMES_COLLECTION, ifreame_item = ifreame_item)

if __name__ == '__main__':
    pass

dmdma/templates/iframes/home.html
{% extends 'iframes/master.html' %}

{% block content %}
<p>Welcome to the iFrames page</p>
<!-- iFrame Item -->
{% if ifreame_item %}
<p>{{ ifreame_item.name }}: {{ ifreame_item.description }}</p>
<iframe src="{{ ifreame_item.url }}"
      title="{{ ifreame_item.name }}"
      width=100%
      style="height: 75vh"
      ></iframe>
{% endif %}
<!-- End: iFrame Item -->
{% endblock %}

dmdma/templates/iframes/master.html
{% extends 'master.html' %}

{%- block application_navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Application Name -->
    <a class="navbar-brand" href="{{ url_for('iframes.home') }}">iframes</a>

    <!-- Button for if page is too narrow for all items -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarApplication" aria-controls="navbarApplication" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Button controlled items -->
    <div class="collapse navbar-collapse" id="navbarApplication">
        <!-- List of Applications -->
        <ul class="navbar-nav mr-auto">
        <!-- Sub Item -->
{#- Using the length of the range to get back an ID for the sub page #}
{%- for i in range(iframes_collection| length) %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('iframes.if_item', iframe_id=i) }}">{{ iframes_collection[i]['name'] }}</a></li>
{%- endfor %}
        <!-- End: Sub Item -->
        </ul>
    </div>
</nav>
{%- endblock %}

{% block content %}
<p>Mapping Data content goes here</p>
{% endblock %}