dmdma/applications/mapping_data_crud/models.py
# Inspired by: https://www.askpython.com/python-modules/flask/flask-crud-application
# Original objects from existing database using: https://pypi.org/project/sqlacodegen/

from flask_sqlalchemy import SQLAlchemy

from . import config

db = SQLAlchemy()

class Entity(db.Model):
    __tablename__ = 'entities'
    __bind_key__ = config.DATABASE_BIND_KEY

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    reference = db.Column(db.Text, nullable=False, unique=True)
    description = db.Column(db.Text)
    date_created = db.Column(db.DateTime, nullable=False, server_default=db.sql.func.now())

    def __init__(self, reference, description = None):
        self.reference = reference
        self.description = description
 
    def __repr__(self):
        return f"{self.id}:{self.reference}"

class EntityGroupMapping(db.Model):
    __tablename__ = 'entity_group_mappings'
    __bind_key__ = config.DATABASE_BIND_KEY

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    entity_id = db.Column(db.ForeignKey("entities.id"), nullable=False)
    group_id = db.Column(db.ForeignKey("groups.id"), nullable=False)
    date_created = db.Column(db.DateTime, nullable=False, server_default=db.sql.func.now())
    
    db.UniqueConstraint(entity_id, group_id)
    
    entity = db.relationship("Entity")
    group = db.relationship("Group")

    def __init__(self, entity_id, group_id):
        self.entity_id = entity_id
        self.group_id = group_id
 
    def __repr__(self):
        return f"{self.id}:{self.entity_id}-{self.group_id}"

class Group(db.Model):
    __tablename__ = 'groups'
    __bind_key__ = config.DATABASE_BIND_KEY

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    reference = db.Column(db.Text, nullable=False, unique=True)
    description = db.Column(db.Text)
    date_created = db.Column(db.DateTime, nullable=False, server_default=db.sql.func.now())

    def __init__(self, reference, description = None):
        self.reference = reference
        self.description = description
 
    def __repr__(self):
        return f"{self.id}:{self.reference}"

if __name__ == '__main__':
    pass

dmdma/applications/mapping_data_crud/__init__.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask.cli import with_appcontext

from . import config

from .models import db as crud_db
from .models import Entity, EntityGroupMapping, Group

from pickle import NONE


bp = Blueprint('mapping_data_crud', __name__, url_prefix='/mapping_data_crud')

# Inspired by
#https://www.askpython.com/python-modules/flask/flask-crud-application

@with_appcontext
@bp.route('/')
def home():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    return render_template('mapping_data_crud/home.html')

################################################################################
# Entity is done in a more monolithic style 
################################################################################
@with_appcontext
@bp.route('/entities')
@bp.route('/entity')
@bp.route('/entity/<int:entity_id>')
@bp.route('/entity/<int:entity_id>/<string:entity_action>', methods = ['GET','POST'])
def entity(entity_id = None, entity_action = 'retrieve'):
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    allowed_actions = ['retrieve','update','delete'] # create handled independently
    error_message = None

    if entity_action not in allowed_actions:
        error_message = 'Unrecognised Action: ' + str(entity_action)

    if entity_id is not None and entity_action == 'retrieve':
        returned_entity = Entity.query.filter_by(id=int(entity_id)).first()
        if returned_entity:
            return render_template('mapping_data_crud/entities.html', individual_entity = returned_entity, retrieve_entity = True)

        error_message = 'Entity not found : ' + str(entity_id)

    if entity_id is not None and entity_action == 'update':
        returned_entity = Entity.query.filter_by(id=int(entity_id)).first()
        if returned_entity:
            if request.method == 'POST':
                returned_entity.reference = request.form['entity_reference']
                returned_entity.description = request.form['entity_description']
                crud_db.session.commit()
                return redirect(url_for('mapping_data_crud.entity', entity_id=returned_entity.id, entity_action='retrieve'))
            
            return render_template('mapping_data_crud/entities.html', individual_entity = returned_entity, update_entity = True)

        error_message = 'Entity not found : ' + str(entity_id)

    if entity_id is not None and entity_action == 'delete':
        returned_entity = Entity.query.filter_by(id=int(entity_id)).first()
        if returned_entity:
            if request.method == 'POST' and request.form['entity_delete_verification'] == "true":
                crud_db.session.delete(returned_entity)
                crud_db.session.commit()
                return redirect(url_for('mapping_data_crud.entity'))

            return render_template('mapping_data_crud/entities.html', individual_entity = returned_entity, delete_entity = True, retrieve_entity = True)

        error_message = 'Entity not found : ' + str(entity_id)
    
    entities = Entity.query.all()
    return render_template('mapping_data_crud/entities.html', entities = entities, error_message = error_message, show_create_btn = True)

@with_appcontext
@bp.route('/entity/create', methods = ['GET','POST'])
def entity_create():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    if request.method == 'GET':
        return render_template('mapping_data_crud/entities.html', create_entity = True)
 
    if request.method == 'POST':
        new_reference = request.form['entity_reference']
        new_description = request.form['entity_description']
        new_entity = Entity(reference=new_reference, description=new_description)
        crud_db.session.add(new_entity)
        crud_db.session.commit()
        
        return redirect(url_for('mapping_data_crud.entity', entity_id=new_entity.id, entity_action='retrieve'))
    
    error_message = 'not yet implemented'
    return render_template('mapping_data_crud/entities.html', error_message = error_message)

################################################################################
# Group is done is a more split out style
################################################################################

@with_appcontext
@bp.route('/groups')
@bp.route('/group')
def group():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    groups = Group.query.all()
    return render_template('mapping_data_crud/group.html', groups = groups)

@with_appcontext
@bp.route('/group/create', methods = ['GET','POST'])
def group_create():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    error_message = None
    
    if request.method == 'GET':
        return render_template('mapping_data_crud/group_create.html')
 
    if request.method == 'POST':
        new_reference = request.form['group_reference']
        new_description = request.form['group_description']
        new_group = Group(reference=new_reference, description=new_description)
        crud_db.session.add(new_group)
        crud_db.session.commit()
        
        return redirect(url_for('mapping_data_crud.group_retrieve', group_id=new_group.id))

    error_message = "Something went wrong"
    return render_template('mapping_data_crud/group.html', error_message = error_message)


@with_appcontext
@bp.route('/group/<int:group_id>')
@bp.route('/group/<int:group_id>/retrieve')
def group_retrieve(group_id):
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    error_message = None
    
    if group_id is not None:
        returned_group = Group.query.filter_by(id=int(group_id)).first()
        if returned_group:
            return render_template('mapping_data_crud/group_retrieve.html', individual_group = returned_group)
    
    error_message = "No group found for ID: " + str(group_id)
    return render_template('mapping_data_crud/group.html', error_message = error_message)

@with_appcontext
@bp.route('/group/<int:group_id>/update', methods = ['GET','POST'])
def group_update(group_id):
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    error_message = None
    
    if group_id is not None:
        returned_group = Group.query.filter_by(id=int(group_id)).first()
        if returned_group:
            if request.method == 'POST':
                returned_group.reference = request.form['group_reference']
                returned_group.description = request.form['group_description']
                crud_db.session.commit()
                return redirect(url_for('mapping_data_crud.group_retrieve', group_id=returned_group.id))
            
            return render_template('mapping_data_crud/group_update.html', individual_group = returned_group)
    
    error_message = "No group found for ID: " + str(group_id)
    return render_template('mapping_data_crud/group.html', error_message = error_message)

@with_appcontext
@bp.route('/group/<int:group_id>/delete', methods = ['GET','POST'])
def group_delete(group_id):
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    error_message = None
    
    if group_id is not None:
        returned_group = Group.query.filter_by(id=int(group_id)).first()
        if returned_group:
            if request.method == 'POST' and request.form['group_delete_verification'] == "true":
                crud_db.session.delete(returned_group)
                crud_db.session.commit()
                return redirect(url_for('mapping_data_crud.group'))
            
            return render_template('mapping_data_crud/group_delete.html', individual_group = returned_group)
    
    error_message = "No group found for ID: " + str(group_id)
    return render_template('mapping_data_crud/group.html', error_message = error_message)

@with_appcontext
@bp.route('/mappings')
@bp.route('/mapping')
def mapping():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    mappings = EntityGroupMapping.query.all()
    return render_template('mapping_data_crud/mapping.html', mappings = mappings)

@with_appcontext
@bp.route('/mapping/create', methods = ['GET','POST'])
def mapping_create():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))
    
    error_message = None
    
    if request.method == 'GET':
        entities = Entity.query.all()
        groups = Group.query.all()
        return render_template('mapping_data_crud/mapping_create.html', entities = entities, groups = groups)
 
    if request.method == 'POST':
        new_entity_id = request.form['mapping_entity_id']
        new_group_id = request.form['mapping_group_id']
        new_mapping = EntityGroupMapping(entity_id=new_entity_id, group_id=new_group_id)
        crud_db.session.add(new_mapping)
        crud_db.session.commit()

dmdma/auth.py
'''
Created on 13 Jul 2022

@author: davidroman-halliday
'''

import functools
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash
from markupsafe import escape
from dmdma.db import get_db

#Not good for prod, but handy for testing
from dmdma.db import init_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

def logout_actions():
    session.clear()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = escape(request.form['username'])
        password = escape(request.form['password'])
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, password) VALUES (?, ?)",
                    (username, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = escape(request.form['username'])
        password = escape(request.form['password'])
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('homepage'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()

@bp.route('/logout')
def logout():
    logout_actions()
    return redirect(url_for('homepage'))

@bp.route('/reset_db')
def reset_db():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    # This shouldn't be used in a production application
    init_db()

    logout_actions()
    return redirect(url_for('auth.login'))

if __name__ == '__main__':
    pass

dmdma/templates/mapping_data_crud/entities.html
{% extends 'mapping_data_crud/master.html' %}

{%- block head_custom %}
<!-- links for CSV Download -->
<script type="text/javascript" src="{{ url_for('static', filename='csv_table_downloader.js') }}"></script>
{%- endblock %}

{% block content %}
<h1>Entities</h1>

{%- if error_message %}
<!-- Error Message -->

<h2>Error</h2>
<p>{{ error_message }}</p>

<!-- End: Error Message -->
{% endif %}


{%- if create_entity %}
<!-- Create New Entity -->

<h2>Create Entity</h2>
<div class="row align-items-start">
  <div class="col-4">
  <form method="post">
    <div class="mb-3">
        <label for="reference" class="form-label">reference</label>
        <input name="entity_reference" class="form-control" id="reference" required>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">description</label>
        <input name="entity_description" class="form-control" id="description" required>
    </div>
    <div class="mb-3">
        <input type="submit" value="Create" class="btn btn-primary">
    </div>
  </form>
  </div>
</div>

<!-- End: Create New Entity -->
{% endif %}

{%- if individual_entity and retrieve_entity %}
<!-- Retrieve Individual Item -->

<h2>Entity Information</h2>
<dl>
    <dt>ID</dt>
    <dd><a href='{{ url_for('mapping_data_crud.entity') }}/{{ individual_entity.id }}'>{{ individual_entity.id }}</a></dd>
    <dt>reference</dt>
    <dd>{{ individual_entity.reference }}</dd>
    <dt>description</dt>
    <dd>{{ individual_entity.description }}</dd>
    <dt>date_created</dt>
    <dd>{{ individual_entity.date_created }}</dd>
</dl>

<!-- End: Retrieve Individual Item -->
{% endif %}


{%- if individual_entity and update_entity %}
<!-- Update Individual Item -->

<h2>Update Entity</h2>
<div class="row align-items-start">
  <div class="col-4">
  <form method="post">
    <div class="mb-3">
        <label for="id" class="form-label">ID</label>
        <input name="entity_id" class="form-control" id="id" value="{{ individual_entity.id }}" required disabled>
    </div>
    <div class="mb-3">
        <label for="reference" class="form-label">reference</label>
        <input name="entity_reference" class="form-control" id="reference" value="{{ individual_entity.reference }}" required>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">description</label>
        <input name="entity_description" class="form-control" id="description" value="{{ individual_entity.description }}" required>
    </div>
    <div class="mb-3">
        <label for="date_created" class="form-label">date_created</label>
        <input name="entity_date_created" class="form-control" id="date_created" value="{{ individual_entity.date_created }}" required disabled>
    </div>
    <div class="mb-3">
        <input type="submit" value="Update" class="btn btn-primary">
    </div>
  </form>
  </div>
</div>

<!-- End: Update Individual Item -->
{% endif %}

{%- if individual_entity and delete_entity %}
<!-- Delete Individual Item -->

<h2>Delete Entity</h2>
<p>Click YES to confirm Deletion</p>
<form action='' method="post" class='pb-2'>
    <input type="hidden" name="entity_delete_verification" id="verification" value="true" >
    <input type = "submit" value="YES" class="btn btn-warning">
</form>

<form action="{{ url_for('mapping_data_crud.entity', entity_id=individual_entity.id, entity_action='retrieve') }}" class='pb-2'>
<button class="btn btn-primary">Cancel</button>
</form>

<!-- End: Delete Individual Item -->
{% endif %}

{%- if entities %}
<!-- Output Items -->

<h2>Entity List</h2>
<table id='entity_list' class='table table-striped table-hover table-sm'>
<tr class='thead-dark text-center'>
    <th>ID</th>
    <th>Reference</th>
    <th>Description</th>
    <th>Date Created</th>
<tr>
{% for entity in entities %}
<tr>
    <td><a href='{{ url_for('mapping_data_crud.entity') }}/{{ entity.id }}'>{{ entity.id }}</a></td>
    <td>{{ entity.reference }}</td>
    <td>{{ entity.description }}</td>
    <td>{{ entity.date_created }}</td>
</tr>
{% endfor %}
</table>
<!-- CSV Download Button -->
<button class="btn btn-primary" id="entity_list_btn_download_csv">Download as CSV</button>
<!-- End: CSV Download Button -->
<!-- CSV Download Button Code -->
<script>
const table_entity_list = document.getElementById('entity_list');
const exportBtn_entity_list = document.getElementById('entity_list_btn_download_csv');

exportBtn_entity_list.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table_entity_list);

    // Download it
    download(csv, 'entities_list_export.csv');
});
</script>
<!-- End: CSV Download Button Code -->

<!-- End: Output Items -->
{% endif %}

{%- if not delete_entity %}
<h2>Entity Actions</h2>

{%- if show_create_btn %}
<form action="{{ url_for('mapping_data_crud.entity_create') }}" class='pb-2'>
<button class="btn btn-primary">Create New Entity</button>
</form>
{% endif %}

{%- if individual_entity %}
<form action="{{ url_for('mapping_data_crud.entity', entity_id=individual_entity.id, entity_action='retrieve') }}" class='pb-2'>
<button class="btn btn-primary">Retrieve (view) This Entity</button>
</form>
<form action="{{ url_for('mapping_data_crud.entity', entity_id=individual_entity.id, entity_action='update') }}" class='pb-2'>
<button class="btn btn-primary">Update This Entity</button>
</form>
<form action="{{ url_for('mapping_data_crud.entity', entity_id=individual_entity.id, entity_action='delete') }}" class='pb-2'>
<button class="btn btn-primary">Delete This Entity</button>
</form>
<form action="{{ url_for('mapping_data_crud.entity') }}" class='pb-2'>
<button class="btn btn-primary">View All Entities</button>
</form>
{% endif %}

{% endif %}

{%- endblock %}

dmdma/templates/mapping_data_crud/group.html
{% extends 'mapping_data_crud/master.html' %}

{%- block head_custom %}
<!-- links for CSV Download -->
<script type="text/javascript" src="{{ url_for('static', filename='csv_table_downloader.js') }}"></script>
{%- endblock %}

{% block content %}
<h1>Groups</h1>

{%- if error_message %}
<!-- Error Message -->

<h2>Error</h2>
<p>{{ error_message }}</p>

<!-- End: Error Message -->
{% endif %}


{% block sub_content %}
{%- if groups %}
<!-- Output Items -->

<h2>Group List</h2>
<table id='group_list' class='table table-striped table-hover table-sm'>
<tr class='thead-dark text-center'>
    <th>ID</th>
    <th>Reference</th>
    <th>Description</th>
    <th>Date Created</th>
<tr>
{% for group in groups %}
<tr>
    <td><a href='{{ url_for('mapping_data_crud.group_retrieve', group_id=group.id) }}'>{{ group.id }}</a></td>
    <td>{{ group.reference }}</td>
    <td>{{ group.description }}</td>
    <td>{{ group.date_created }}</td>
</tr>
{% endfor %}
</table>
<!-- CSV Download Button -->
<button class="btn btn-primary" id="group_list_btn_download_csv">Download as CSV</button>
<!-- End: CSV Download Button -->
<!-- CSV Download Button Code -->
<script>
const table_group_list = document.getElementById('group_list');
const exportBtn_group_list = document.getElementById('group_list_btn_download_csv');

exportBtn_group_list.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table_group_list);

    // Download it
    download(csv, 'groups_list_export.csv');
});
</script>
<!-- End: CSV Download Button Code -->

<!-- End: Output Items -->
{% endif %}
{%- endblock %}

{% block group_actions %}
<h2>Actions</h2>
{%- if individual_group %}
<form action="{{ url_for('mapping_data_crud.group_retrieve', group_id=individual_group.id) }}" class='pb-2'>
<button class="btn btn-primary">Retrieve (view) This Group</button>
</form>
<form action="{{ url_for('mapping_data_crud.group_update', group_id=individual_group.id) }}" class='pb-2'>
<button class="btn btn-primary">Update This Group</button>
</form>
<form action="{{ url_for('mapping_data_crud.group_delete', group_id=individual_group.id) }}" class='pb-2'>
<button class="btn btn-primary">Delete This Group</button>
</form>
<form action="{{ url_for('mapping_data_crud.group') }}" class='pb-2'>
<button class="btn btn-primary">View All groups</button>
</form>
{% else %}
<form action="{{ url_for('mapping_data_crud.group_create') }}" class='pb-2'>
<button class="btn btn-primary">Create New Group</button>
</form>
{% endif %}
{%- endblock %}

{%- endblock %}

dmdma/templates/mapping_data_crud/group_create.html
{% extends 'mapping_data_crud/group.html' %}

{% block sub_content %}
<!-- Create New Group -->

<h2>Create Group</h2>
<div class="row align-items-start">
  <div class="col-4">
  <form method="post">
    <div class="mb-3">
        <label for="reference" class="form-label">reference</label>
        <input name="group_reference" class="form-control" id="reference" required>
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">description</label>
        <input name="group_description" class="form-control" id="description" required>
    </div>
    <div class="mb-3">
        <input type="submit" value="Create" class="btn btn-primary">
    </div>
  </form>
  </div>
</div>

<!-- End: Create New Group -->
{%- endblock %}

dmdma/templates/mapping_data_crud/group_retrieve.html
{% extends 'mapping_data_crud/group.html' %}

{% block sub_content %}

{%- if individual_group %}
<!-- Retrieve Individual Item -->

<h2>Group Information</h2>
<dl>
    <dt>ID</dt>
    <dd><a href='{{ url_for('mapping_data_crud.group_retrieve', group_id=individual_group.id) }}'>{{ individual_group.id }}</a></dd>
    <dt>reference</dt>
    <dd>{{ individual_group.reference }}</dd>
    <dt>description</dt>
    <dd>{{ individual_group.description }}</dd>
    <dt>date_created</dt>
    <dd>{{ individual_group.date_created }}</dd>
</dl>

<!-- End: Retrieve Individual Item -->
{% endif %}

{%- endblock %}

dmdma/templates/mapping_data_crud/home.html
{% extends 'mapping_data_crud/master.html' %}

{% block content %}
<p>Welcome to the Mapping Data CRUD page</p>
{% endblock %}

dmdma/templates/mapping_data_crud/mapping.html
{% extends 'mapping_data_crud/master.html' %}

{%- block head_custom %}
<!-- links for CSV Download -->
<script type="text/javascript" src="{{ url_for('static', filename='csv_table_downloader.js') }}"></script>
{%- endblock %}

{% block content %}
<h1>mappings</h1>

{%- if error_message %}
<!-- Error Message -->

<h2>Error</h2>
<p>{{ error_message }}</p>

<!-- End: Error Message -->
{% endif %}


{% block sub_content %}
{%- if mappings %}
<!-- Output Items -->

<h2>mapping List</h2>
<table id='mapping_list' class='table table-striped table-hover table-sm'>
<tr class='thead-dark text-center'>
    <th>ID</th>
    <th>Entity ID</th>
    <th>Group ID</th>
    <th>Date Created</th>
<tr>
{% for mapping in mappings %}
<tr>
    <td><a href='{{ url_for('mapping_data_crud.mapping_retrieve', mapping_id=mapping.id) }}'>{{ mapping.id }}</a></td>
    <td>{{ mapping.entity_id }}</td>
    <td>{{ mapping.group_id }}</td>
    <td>{{ mapping.date_created }}</td>
</tr>
{% endfor %}
</table>
<!-- CSV Download Button -->
<button class="btn btn-primary" id="mapping_list_btn_download_csv">Download as CSV</button>
<!-- End: CSV Download Button -->
<!-- CSV Download Button Code -->
<script>
const table_mapping_list = document.getElementById('mapping_list');
const exportBtn_mapping_list = document.getElementById('mapping_list_btn_download_csv');

exportBtn_mapping_list.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table_mapping_list);

    // Download it
    download(csv, 'mappings_list_export.csv');
});
</script>
<!-- End: CSV Download Button Code -->

<!-- End: Output Items -->
{% endif %}
{%- endblock %}

{% block mapping_actions %}
<h2>Actions</h2>
{%- if individual_mapping %}
<form action="{{ url_for('mapping_data_crud.mapping_retrieve', mapping_id=individual_mapping.id) }}" class='pb-2'>
<button class="btn btn-primary">Retrieve (view) This mapping</button>
</form>
<form action="{{ url_for('mapping_data_crud.mapping_update', mapping_id=individual_mapping.id) }}" class='pb-2'>
<button class="btn btn-primary">Update This mapping</button>
</form>
<form action="{{ url_for('mapping_data_crud.mapping_delete', mapping_id=individual_mapping.id) }}" class='pb-2'>
<button class="btn btn-primary">Delete This mapping</button>
</form>
<form action="{{ url_for('mapping_data_crud.mapping') }}" class='pb-2'>
<button class="btn btn-primary">View All mappings</button>
</form>
{% else %}
<form action="{{ url_for('mapping_data_crud.mapping_create') }}" class='pb-2'>
<button class="btn btn-primary">Create New mapping</button>
</form>
{% endif %}
{%- endblock %}

{%- endblock %}

dmdma/templates/mapping_data_crud/master.html
{% extends 'master.html' %}

{%- block application_navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Application Name -->
    <a class="navbar-brand" href="{{ url_for('mapping_data_crud.home') }}">Mapping Data CRUD</a>

    <!-- Button for if page is too narrow for all items -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarApplication" aria-controls="navbarApplication" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Button controlled items -->
    <div class="collapse navbar-collapse" id="navbarApplication">
        <!-- List of Applications -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('mapping_data_crud.entity') }}">Entities</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('mapping_data_crud.group') }}">Groups</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('mapping_data_crud.mapping') }}">Entity Group Mappings</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('mapping_data_crud.reset_db') }}">Reset Database</a></li>
        </ul>
    </div>
</nav>
{%- endblock %}

{% block content %}
<p>Mapping Data content goes here</p>
{% endblock %}