dmdma/applications/reporting/__init__.py
import functools
import os

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask import current_app
from flask.cli import with_appcontext

from markupsafe import escape


import sqlite3
import pandas

bp = Blueprint('reporting', __name__, url_prefix='/reporting')

TEST_DATABASE_NAME='dmdma_test_db.sqlite'

def beautify_html_table(html_table : str, table_id :str = 'exportMe', center_headings : bool = True):
    """Apply common formatting to the pandas created HTML,including an ID for javascript manipulation """

    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html_table, "html.parser")
    soup.find('table')['id'] = table_id
    soup.find('table')['class'] = 'table table-striped table-hover table-sm'
    soup.find('thead')['class'] = 'thead-dark'

    soup.find('tr')['style'] = None

    if center_headings:
        for si in soup.find_all('th'):
            si['class'] = 'text-center'

    #html_output = soup.prettify()
    html_output = str(soup)
    return html_output

@with_appcontext
@bp.route('/')
def home():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    return render_template('reporting/home.html')

@with_appcontext
@bp.route('/reset_db')
def reset_db():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    with current_app.open_resource('data/reporting/testing_schema.sql') as f:
        db.executescript(f.read().decode('utf8'))

    show_tables_sql = "SELECT name FROM sqlite_master WHERE type='table';"

    pandas_result_set = pandas.read_sql_query(show_tables_sql, db)
    pandas_resultset_html = pandas_result_set.to_html(index = False)

    beautiful_html_table = beautify_html_table(pandas_resultset_html)

    if db is not None:
        db.close

    return render_template('reporting/reset_db.html', table=beautiful_html_table)

@with_appcontext
@bp.route('/pivot_sample')
def pivot_sample():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    get_data_sql = "SELECT * FROM testing;"
    pandas_result_set = pandas.read_sql_query(get_data_sql, db)

    beautiful_html_table = beautify_html_table(pandas_result_set.to_html(index = False))

    pandas_resultset_json = pandas_result_set.to_json(orient = 'records')

    if db is not None:
        db.close

    return render_template('reporting/pivot.html', table=beautiful_html_table, json_data=pandas_resultset_json)

@with_appcontext
@bp.route('/dynamic_sample_1')
def dynamic_sample_1():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    from . import item

    get_data_sql = "SELECT * FROM testing;"

    report_part_1 = item.item(title='Testing report 1')
    report_part_1.htmlTableID = 'rep_1'
    report_part_1.introText = '<p>This goes before the table</p>'
    report_part_1.introTextIsHTML = True
    report_part_1.outroText = 'This goes after the table'
    report_part_1.dataFrame = pandas.read_sql_query(get_data_sql, db)
    report_part_1.htmlTable = beautify_html_table(report_part_1.dataFrame.to_html(index = False),
                                                  table_id = report_part_1.htmlTableID
                                                  )


    get_data_sql = "SELECT * FROM testing_2;"

    report_part_2 = item.item(title='Testing report 2',
                                    dataFrame = pandas.read_sql_query(get_data_sql, db),
                                    )
    report_part_2.htmlTable = beautify_html_table(report_part_2.dataFrame.to_html(index = False),
                                                  table_id = report_part_2.htmlTableID
                                                  )


    report_page_title = 'Testing Reports'
    reporting_table_sets = [report_part_1,
                            report_part_2
                           ]

    return render_template('reporting/reporting_items.html',
                           report_page_title = report_page_title,
                           reporting_table_sets = reporting_table_sets
                           )

@with_appcontext
@bp.route('/dynamic_sample_2')
def dynamic_sample_2():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    from . import item

    get_data_sql = "SELECT value_2, SUM(metric_1) AS metric_1_sum FROM testing GROUP BY value_2;"

    report_part_1 = item.item(title='Aggregate Report',
                                    dataFrame = pandas.read_sql_query(get_data_sql, db),
                                    )
    report_part_1.convertToBeautifulHTML()


    report_page_title = 'Testing Reports 2'
    reporting_table_sets = [report_part_1
                           ]

    return render_template('reporting/reporting_items.html',
                           report_page_title = report_page_title,
                           reporting_table_sets = reporting_table_sets
                           )

if __name__ == '__main__':
    pass

dmdma/reporting/__init__.py
import functools
import os

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask import current_app
from flask.cli import with_appcontext

from markupsafe import escape


import sqlite3
import pandas

bp = Blueprint('reporting', __name__, url_prefix='/reporting')

TEST_DATABASE_NAME='dmdma_test_db.sqlite'

def beautify_html_table(html_table : str, table_id :str = 'exportMe', center_headings : bool = True):
    """Apply common formatting to the pandas created HTML,including an ID for javascript manipulation """

    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html_table, "html.parser")
    soup.find('table')['id'] = table_id
    soup.find('table')['class'] = 'table table-striped table-hover table-sm'
    soup.find('thead')['class'] = 'thead-dark'

    soup.find('tr')['style'] = None

    if center_headings:
        for si in soup.find_all('th'):
            si['class'] = 'text-center'

    #html_output = soup.prettify()
    html_output = str(soup)
    return html_output

@with_appcontext
@bp.route('/')
def home():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    return render_template('reporting/home.html')

@with_appcontext
@bp.route('/reset_db')
def reset_db():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    with current_app.open_resource('data/reporting/testing_schema.sql') as f:
        db.executescript(f.read().decode('utf8'))

    show_tables_sql = "SELECT name FROM sqlite_master WHERE type='table';"

    pandas_result_set = pandas.read_sql_query(show_tables_sql, db)
    pandas_resultset_html = pandas_result_set.to_html(index = False)

    beautiful_html_table = beautify_html_table(pandas_resultset_html)

    if db is not None:
        db.close

    return render_template('reporting/reset_db.html', table=beautiful_html_table)

@with_appcontext
@bp.route('/pivot_sample')
def pivot_sample():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    get_data_sql = "SELECT * FROM testing;"
    pandas_result_set = pandas.read_sql_query(get_data_sql, db)

    beautiful_html_table = beautify_html_table(pandas_result_set.to_html(index = False))

    pandas_resultset_json = pandas_result_set.to_json(orient = 'records')

    if db is not None:
        db.close

    return render_template('reporting/pivot.html', table=beautiful_html_table, json_data=pandas_resultset_json)

@with_appcontext
@bp.route('/dynamic_sample_1')
def dynamic_sample_1():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    from dmdma.reporting import item

    get_data_sql = "SELECT * FROM testing;"

    report_part_1 = item.item(title='Testing report 1')
    report_part_1.htmlTableID = 'rep_1'
    report_part_1.introText = '<p>This goes before the table</p>'
    report_part_1.introTextIsHTML = True
    report_part_1.outroText = 'This goes after the table'
    report_part_1.dataFrame = pandas.read_sql_query(get_data_sql, db)
    report_part_1.htmlTable = beautify_html_table(report_part_1.dataFrame.to_html(index = False),
                                                  table_id = report_part_1.htmlTableID
                                                  )


    get_data_sql = "SELECT * FROM testing_2;"

    report_part_2 = item.item(title='Testing report 2',
                                    dataFrame = pandas.read_sql_query(get_data_sql, db),
                                    )
    report_part_2.htmlTable = beautify_html_table(report_part_2.dataFrame.to_html(index = False),
                                                  table_id = report_part_2.htmlTableID
                                                  )


    report_page_title = 'Testing Reports'
    reporting_table_sets = [report_part_1,
                            report_part_2
                           ]

    return render_template('reporting/reporting_items.html',
                           report_page_title = report_page_title,
                           reporting_table_sets = reporting_table_sets
                           )

@with_appcontext
@bp.route('/dynamic_sample_2')
def dynamic_sample_2():
    # Redirect to login if no user logged in
    # ToDo: Add logic to see if user has access to application
    if g.user is None:
        return redirect(url_for('auth.login'))

    TEST_DATABASE = os.path.join(current_app.instance_path, TEST_DATABASE_NAME)

    db = sqlite3.connect(
            TEST_DATABASE,
            detect_types=sqlite3.PARSE_DECLTYPES
        )

    from dmdma.reporting import item

    get_data_sql = "SELECT value_2, SUM(metric_1) AS metric_1_sum FROM testing GROUP BY value_2;"

    report_part_1 = item.item(title='Aggregate Report',
                                    dataFrame = pandas.read_sql_query(get_data_sql, db),
                                    )
    report_part_1.convertToBeautifulHTML()


    report_page_title = 'Testing Reports 2'
    reporting_table_sets = [report_part_1
                           ]

    return render_template('reporting/reporting_items.html',
                           report_page_title = report_page_title,
                           reporting_table_sets = reporting_table_sets
                           )

if __name__ == '__main__':
    pass

dmdma/templates/reporting/home.html
{% extends 'reporting/master.html' %}

{% block content %}
<p>Welcome to the reporting page</p>
{% endblock %}

dmdma/templates/reporting/master.html
{% extends 'master.html' %}

{%- block application_navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Application Name -->
    <a class="navbar-brand" href="{{ url_for('reporting.home') }}">Reporting</a>

    <!-- Button for if page is too narrow for all items -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarApplication" aria-controls="navbarApplication" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Button controlled items -->
    <div class="collapse navbar-collapse" id="navbarApplication">
        <!-- List of Applications -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('reporting.dynamic_sample_1') }}">Dynamic Reporting 1</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('reporting.dynamic_sample_2') }}">Dynamic Reporting 2</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('reporting.pivot_sample') }}">PivotTable</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('reporting.reset_db') }}">Reset Database</a></li>
        </ul>
    </div>
</nav>
{%- endblock %}

{% block content %}
<p>reporting content goes here</p>
{% endblock %}

dmdma/templates/reporting/pivot.html
{% extends 'reporting/master.html' %}

{%- block head_custom %}
<!-- links for CSV Download -->
<script type="text/javascript" src="{{ url_for('static', filename='csv_table_downloader.js') }}"></script>
<!-- links for Pivot table -->
<link href="https://cdn.webdatarocks.com/latest/webdatarocks.min.css" rel="stylesheet"/>
<script src="https://cdn.webdatarocks.com/latest/webdatarocks.toolbar.min.js"></script>
<script src="https://cdn.webdatarocks.com/latest/webdatarocks.js"></script>
{%- endblock %}

{% block content %}
<!-- Data table -->
<h1>Data Table</h1>
{{ table | safe }}

<!-- CSV Download Button -->
<button class="btn btn-primary" id="export">Download as CSV</button>
<!-- CSV Download Script (leverages library above) -->
<script>
const table = document.getElementById('exportMe');
const exportBtn = document.getElementById('export');

exportBtn.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table);

    // Download it
    download(csv, 'test_list_tables.csv');
});
</script>

<!-- Pivot table -->
<!-- https://www.webdatarocks.com/doc/json-data-source/ -->
<h1>Pivot Table</h1>
<p>Using code from <a href="https://www.webdatarocks.com/">webdatarocks.com</a>.</p>

<div id="wdr-component"></div>

<script>
var myJSONData = {{ json_data | safe }};

var pivot = new WebDataRocks({
    container: "#wdr-component",
    toolbar: true,
    report: {
        dataSource: {
        	data: myJSONData
        }
    }
});
</script>

{%- endblock %}

dmdma/templates/reporting/reporting_items.html
{% extends 'reporting/master.html' %}

{%- block head_custom %}
<!-- links for CSV Download -->
<script type="text/javascript" src="{{ url_for('static', filename='csv_table_downloader.js') }}"></script>
{%- endblock %}

{% block content %}
<h1>Reporting: {% block title %}{{ report_page_title }}{% endblock %}</h1>
<!-- Reporting Items -->
{% for reportItem in reporting_table_sets %}
<!-- Reporting Item -->
<h2>{{ reportItem.title }}</h2>

{% if ( ( reportItem.introTextIsHTML == false ) and ( reportItem.introText is not none ) ) %}
<p>{{ reportItem.introText }}</p>
{% elif ( reportItem.introText is not none ) %}
{{ reportItem.introText | safe }}
{% endif %}

{{ reportItem.htmlTable | safe }}

{% if reportItem.htmlTableCsvDownload == true %}
<!-- CSV Download Button -->
<button class="btn btn-primary" id="btn_{{ reportItem.htmlTableID }}">Download as CSV</button>
<!-- CSV Download Button Code -->
<script>
const table_{{loop.index}} = document.getElementById('{{ reportItem.htmlTableID }}');
const exportBtn_{{loop.index}} = document.getElementById('btn_{{ reportItem.htmlTableID }}');

exportBtn_{{loop.index}}.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table_{{loop.index}});

    // Download it
    download(csv, '{{ reportItem.title | replace(" ", "_") }}.csv');
});
</script>
{% endif %}

{% if ( ( reportItem.outroTextIsHTML == false ) and ( reportItem.outroText is not none ) ) %}
<p>{{ reportItem.outroText }}</p>
{% elif ( reportItem.outroText is not none ) %}
{{ reportItem.outroText | safe }}
{% endif %}

<!-- End: Reporting Item -->
{% endfor %}
<!-- End: Reporting Items -->

{%- endblock %}

dmdma/templates/reporting/reset_db.html
{% extends 'reporting/master.html' %}

{% block content %}
<h1>Database reset</h1>

<p>The database has been reset</p>

{{ table | safe }}

<button class="btn btn-primary" id="export">Download as CSV</button>

<!-- Export CSV Code (all embedded rather than linked)-->
<script>
const toCsv = function (table) {
    // Query all rows
    const rows = table.querySelectorAll('tr');

    return [].slice
        .call(rows)
        .map(function (row) {
            // Query all cells
            const cells = row.querySelectorAll('th,td');
            return [].slice
                .call(cells)
                .map(function (cell) {
                    return cell.textContent;
                })
                .join(',');
        })
        .join('\n');
};

const download = function (text, fileName) {
    const link = document.createElement('a');
    link.setAttribute('href', `data:text/csv;charset=utf-8,${encodeURIComponent(text)}`);
    link.setAttribute('download', fileName);

    link.style.display = 'none';
    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);
};


const table = document.getElementById('exportMe');
const exportBtn = document.getElementById('export');

exportBtn.addEventListener('click', function () {
    // Export to csv
    const csv = toCsv(table);

    // Download it
    download(csv, 'test_list_tables.csv');
});
</script>
<!-- End: Export CSV Code -->
{% endblock %}